services:
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: es
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "29200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - szt-network

networks:
  szt-network:
    driver: bridge
    name: szt-network
#    attachable: true # driver 为 overlay 时使用, 如果设置为 true 则除了服务之外，独立容器也可以附加到该网络
#    external: true # 一些场景下，我们并不需要创建新的网络，而只需加入已存在的网络，此时可使用external选项，必须提前创建

# docker compose -f es.yaml up -d
